### PR TITLE
Replaced 'bindShared' with 'singleton' for laravel 5.2

### PR DESCRIPTION
**Pull request by nahiyan**
'bindShared' has been replaced with 'singleton' as of laravel 5.2

### CODE REVIEW

**Comment by heydavid713** [comment]
Please be aware that this breaks compatibility with Laravel 5.1

**Comment by nahiyan** [comment]
Yeah it does. I guess a specific version of NeoEloquent has to be released for 5.2.

**Comment by bostinait** [comment]
Will this pull request be accepted perhaps under a different version number to satisfy backwards compatibility?

**Comment by nahiyan** [comment]
Version 2.0 will be out within a week or two. Let's see what happens.

**Comment by coreation** [comment]
Are you sure this is working for L5.2? Because if I try to install your fork, I get the error that the pagination is still at 5.1?

**Comment by Mulkave** [comment]
@nahiyan thanks for the PR! Does that grant backward compatibility?

**Comment by nahiyan** [comment]
@Mulkave unfortunately, no :(

**Comment by Mulkave** [comment]
hmm in that case we can't merge into 1.2.11 and break backward compatibility with 5.0 and 5.1 :confused: I'll release a new version v1.3 to be considered the 5.2 compatible branch

**Comment by Mulkave** [comment]
@nahiyan please re-open your PR to 1.3.0, closing this one.

**Pull request closed without merging**
