### PR TITLE
fix syntax error when building namespaced relation label

### PR DESCRIPTION
**Pull request by apopiak**
see https://github.com/Vinelab/NeoEloquent/pull/109 for the original fix

### CODE REVIEW

**Comment by apopiak** [comment]
@Mulkave 
I'm not sure why the tests fail, care to enlighten me?

**Comment by apopiak** [comment]
Will there be a 1.3 release that includes this fix?

**Comment by Mulkave** [comment]
@apopiak sorry closed by mistake. The tests are failing due to an incompatibility with Illuminate's Connection class. Looking into it.

**Comment by apopiak** [comment]
Thanks, very much appreciated!

**Comment by Mulkave** [comment]
Just need a rebase so that we can merge this, better open to 1.4 instead.

**Comment by apopiak** [comment]
rebased onto `1.4` and there was no diff, someone must have fixed it already

**Pull request closed without merging**
