### PR TITLE
add array property support

### PR DESCRIPTION
**Pull request by apopiak**
add array property support

+ stringify arrays in `valufy` and adjust tests
+ add array support to prepareBindings in Connection

ref #197

### CODE REVIEW

**Comment by apopiak** [comment]
@Mulkave 
review? :-)

**Comment by apopiak** [comment]
I get the same error as Travis when trying to execute the tests locally, btw.

**Comment by Mulkave** [comment]
Would love to merge but afraid of doing so and breaking something since we can't tell if the tests won't run 😞

**Comment by Mulkave** [comment]
This is outdated now. Should rebase. If not interested please close.

**Comment by apopiak** [comment]
I no longer really need this, so will close.

**Pull request closed without merging**
