### PR TITLE
Support for Laravel 5.6

### PR DESCRIPTION
**Pull request by holix**
Hi,
this PR is to add support for Laravel 5.6.
It breaks compatibility with older versions of Laravel.

### CODE REVIEW

**Comment by holix** [comment]
@michaelcontento 
I've implemented getMigrationBatches method, and added neo4j:migrate:status command

**Comment by michaelcontento** [comment]
@holix Cool, thanks! Works on my side perfectly 👍

**Comment by Mulkave** [comment]
This is awesome!

How can we provide this without breaking compatibility? Maybe merge on a different branch? If so, let me know so that i create that branch and merge accordingly.

**Comment by holix** [comment]
I think that we should go with different branch.

**Comment by Mulkave** [comment]
Since we're following the releases pattern, where the same branch (1.4) contains the latest and support is specified by release as mentioned in the docs. So this will be 1.4.6+

**Pull request merged**
