### PR TITLE
Patch to fix issue 49 "Where conditions on related entities, case sensitivity issue on the alias in query"

### PR DESCRIPTION
**Pull request by tomb10516**
I changed Grammar::modelAsNode() so that it now downcases only the first character of labels rather than downcasing the entire string.  I believe that this is the correct casing, please let me know if I am wrong.

### CODE REVIEW

**Comment by tomb10516** [comment]
I'm a little confused about the build failures.  These seem to do with 2f297d5 and 89e5292 but I only submitted a pull request for e101d19.  If someone can tell me how to correct this I'll do so.   My company uses gitlab rather than github so I'm just starting to learn about the pull request and auto build system.

**Comment by Mulkave** [comment]
@tomb10516 it really is confusing, even the type hint changes were introduced in 1.2.5 which was merged in https://github.com/tomb10516/NeoEloquent/commit/4877a49335d0b6a6c7e5332f234735870fddd032

**Comment by tomb10516** [comment]
I wondered about that too!  I saw the type hint changes in 4877a49 but the changes weren't applied to my branch when I merged from upstream.  That is why I had to apply the same patch manually.  Should I create a new branch in my repo based on the newest vinelab/1.2.5 and merge into that only ffa8773 and e101d19 and then generate a PR for that?

**Comment by Mulkave** [comment]
@tomb10516 yes let's try that please. Much appreciated :smile:

**Pull request closed without merging**
