### PR TITLE
Fix for migrations

### PR DESCRIPTION
**Pull request by marshy2346**
Migrations were not using the correct stubs

### CODE REVIEW

**Comment by alexislefebvre** [comment]
There is too much commits in this PR, you should probably rebase it.

**Comment by Mulkave** [comment]
can you get the tests passing? it's important to make sure that all is working and that this doesn't break existing code.

**Comment by mcamachon69** [comment]
I do not know why they did not allow this contribution. I just applied it to my project and it helped me with the migration stubs. THANK YOU !!

**Comment by Mulkave** [comment]
@mcamachon69 it was due to the tests not passing. This should've fixed them https://github.com/Vinelab/NeoEloquent/pull/255

**Pull request closed without merging**
