### PR TITLE
Laravel5.4

### PR DESCRIPTION
**Pull request by tomahock**

### CODE REVIEW

**Comment by atodd** [comment]
This would be a much appreciated upgrade

**Comment by aamasri** [comment]
Yes, this would be really appreciated especially for Vinelab/NeoEloquent 1.5-dev.  I want to use this for a new Laravel project and would donate if it would ensure ongoing development of NeoEloquent including integration with graphaware/neo4j-php-client.

**Comment by mihaizzza** [comment]
Does this works with Laravel 5.4?

**Comment by elanvans** [comment]
Problem 1
    - Conclusion: remove laravel/framework v5.4.18
    - Conclusion: don't install laravel/framework v5.4.18
    - vinelab/neoeloquent v1.4.0 requires illuminate/pagination 5.3.* -> satisfiable by illuminate/pagination[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - vinelab/neoeloquent v1.4.1 requires illuminate/pagination 5.3.* -> satisfiable by illuminate/pagination[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - vinelab/neoeloquent v1.4.2 requires illuminate/pagination 5.3.* -> satisfiable by illuminate/pagination[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/pagination v5.3.0|don't install laravel/framework v5.4.18
    - don't install illuminate/pagination v5.3.16|don't install laravel/framework v5.4.18
    - don't install illuminate/pagination v5.3.23|don't install laravel/framework v5.4.18
    - don't install illuminate/pagination v5.3.4|don't install laravel/framework v5.4.18
    - Installation request for laravel/framework (locked at v5.4.18, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.18].
    - Installation request for vinelab/neoeloquent 1.4.* -> satisfiable by vinelab/neoeloquent[v1.4.0, v1.4.1, v1.4.2].

**Comment by Mulkave** [comment]
@aamasri an integration of graphaware/neo4j-php-client was planned but due to being busy recently and not being able to allocate time for NE atm. Would love to review and merge contributions though, but this one isn't passing tests so I would refrain from merging to not break compatibility.

**Comment by tomahock** [comment]
@Mulkave locally the tests pass.. Not sure why they are failing on travis..
I've been using this branch without errors, but I'm not using every feature on my project! 

I think this need e little more work, but the basic is working!

**Comment by Mulkave** [comment]
@tomahock as long as the tests pass locally, means there's full backward compatibility. If you can confirm the tests then we're safe to merge

**Comment by tomahock** [comment]
Well.. it's not 100% pass, but almost!

```
ERRORS!
Tests: 266, Assertions: 1087, Errors: 1, Warnings: 15, Incomplete: 7.```

I'm going to try get some time to try to fix it!

**Comment by Mulkave** [comment]
@tomahock thanks for that, will be waiting for your fix, or if you can link to the branch where these tests exist maybe someone can lend a helping hand fixing that.

**Comment by freemanjackal** [comment]
any update about this, i want to test it for my lumen based on laravel 5.4.*

**Comment by elanvans** [comment]
Please fix this issue.

**Comment by Mulkave** [comment]
5.4 is supported: https://github.com/vinelab/neoeloquent#54

**Pull request closed without merging**
