### PR TITLE
Added support for addLabels() and dropLabels() functions.

### PR DESCRIPTION
**Pull request by sameer-shelavale**

### CODE REVIEW

**Comment by sameer-shelavale** [comment]
@Mulkave please check this one.
I will create one more PR for retrieving all the Labels which was being discussed here
https://github.com/Vinelab/NeoEloquent/issues/29
That will allow to write some unit tests as well.

**Comment by Mulkave** [comment]
@sameer-shelavale can you please provide tests for this implementation ? Thanks.

**Comment by sameer-shelavale** [comment]
@mulkave I will to use Everyman to write the unit tests

**Comment by sameer-shelavale** [comment]
I have created fresh PR at https://github.com/Vinelab/NeoEloquent/pull/45,
closing this PR.

**Pull request closed without merging**
