### PR TITLE
5.7 Version bump

### PR DESCRIPTION
**Pull request by alex-jf**
Trying to add 5.7 support

### CODE REVIEW

**Comment by lucabecchetti** [comment]
Any news?

**Comment by lucabecchetti** [comment]
I do not see anything online!

**Comment by lucabecchetti** [comment]
I'm sorry, do we have to make a fork? is this project been discontinued? or are you plan to make an update? Thanks!

**Comment by alex-jf** [comment]
Just a bit of patience.

**Comment by Mulkave** [comment]
@alex-jf can you confirm this update?

**Comment by lucabecchetti** [comment]
> Just a bit of patience.

News?

**Comment by alex-jf** [comment]
Seems to be working for me on couple of side projects.

**Comment by ivanlukic** [comment]
Any news?

**Comment by Mulkave** [comment]
Reverted due to failing tests https://travis-ci.org/Vinelab/NeoEloquent/jobs/493151963

**Pull request merged**
