### PR TITLE
delete node with relations or not relations

### PR DESCRIPTION
**Pull request by charles7aponte**
delete all node with relations or not relations

### CODE REVIEW

**Comment by Mulkave** [comment]
This was done that way on purpose, the reason is similar to deleting foreign records in a relational database. Though I'm not aware of its application in graph and what's recommended.

Thanks for the PR, What do you think @charles7aponte ?

**Comment by charles7aponte** [comment]
Neo4j v2.2 is eliminated query:

MATCH (n)
OPTIONAL MATCH (n) - [r] - ()
DELETE n, r

delete all nodes and relationships

**Comment by charles7aponte** [comment]
can delete nodes from the model, and have related nodes or not having

**Comment by Mulkave** [comment]
@charles7aponte I get what you mean. Though is this a behaviour that should be there by default? instead of warning the developer about the existence of relationships on the node. I suggest that we implement a different deletion method, i.e. `deleteWithRelations()` or `forceDelete()`.

What do you think?

**Comment by charles7aponte** [comment]
ok . :+1:

**Comment by Mulkave** [comment]
After giving this some thought, it appears to make sense to have it your way instead of not deleting or warning. Merging.

**Pull request merged**
